### ISSUE TITLE
remove datastore configuration options from individual providers

### ISSUE THREAD

**Issue by jgravois** [Esri/koop#108]
i was able to get koop up and running this morning after running the following command in a new folder and copy/pasting your sample server.js file in.

`npm install koop && npm install koop-github && npm install express`

initially i tried substituting SQLite database information and encountered a `no geojson found` error when accessing the sample github url in the README.  after switching to PostGIS datastore (and back) the problem wasn't reproducible again.

my initial suspicion that the problem was caused by datastore configuration info for my github not matching the config object in my server.js file just reminded me that its confusing that they are present in both locations.

https://github.com/chelm/koop-github/issues/9

if whats listed in individual providers is already being ignored, just let me know and i can submit PRs to get rid of them.
cc @ngoldman

**Comment by chelm** [comment]
There should only be one config json that get passed around, and that comes from the highest level. Any configs in providers are completely ignored (or should be!) when a provider is "registered". 

The reason that the configs are still present in the providers is that I havent yet decided what to do with them :) and they are needed to run the tests. What we need to figured out is how to run tests with a config for each provider. Actually now that I say it I think its just a matter of moving them into the test dir and updating the tests to use the new config location. 

Does that make sense? Did I understand what you were talking about?

**Comment by chelm** [comment]
@jgravois I think we should move the configs out of each provider's root dir and into the test dir. The only question is what is the best practice for handling configurations for testing each provider.

**Comment by jgravois** [comment]
that sounds great.  if the tests can pull in configuration info from the same folder i think it makes the architecture of the provider as a whole way more intuitive.
