### ISSUE TITLE
add CHANGELOG.md, tag & release all versions

### ISSUE THREAD

**Issue by ngoldman** [Esri/koop#109]
It's great to see that koop is now versioned and getting pushed to npm! However without a changelog it will be hard for users to follow what's changing from version to version, and without tagged releases it will be hard to keep track of version milestones in the repo.

## changelog

A changelog helps users (and project contributors) know what's going on in a project and what's changing from version to version. http://keepachangelog.com/ has some really good ideas and conventions for how to structure a changelog (better than what I've been doing [recently](https://github.com/ngoldman/gfm.css/blob/gh-pages/CHANGELOG.md)).

## tagged releases

I *strongly* recommend [tagging](https://github.com/Esri/koop/releases) the commits that represent versions pushed to npm. There's no easy way in this repo at present to know what commit in github corresponds to the version on npm.

Another convention that's worth adopting is putting the content of the version changes in the release notes when tagging a new release on github. Here's an [example](https://github.com/ngoldman/gfm.css/releases).

/cc @chelm @jgravois

**Comment by chelm** [comment]
@ngoldman all great stuff! I am slowly able to churn through my lists and will put this on there! 

I did have change logs going for a bit on the old repo: https://github.com/Esri/koop-server/blob/master/CHANGELOG.md - need to get back to some of this debt.

**Comment by ngoldman** [comment]
@chelm thanks, let me know if I can help. I can create the file but I'm not sure what changes have occurred.

**Comment by chelm** [comment]
@ngoldman ch ch ch changes https://github.com/Esri/koop/blob/master/CHANGELOG.md - now I probably need to work on making meaningful commit messages :sheep:

**Comment by ngoldman** [comment]
@chelm So one of the things that http://keepachangelog.com/ recommends not doing is "dumping a diff of commit logs" (in fact the tagline for the entire site is "Don’t let your friends dump git logs into CHANGELOGs™").

**Comment by chelm** [comment]
@ngoldman you mean you expect me to actually read the *words* on the sites you link to?

**Comment by ngoldman** [comment]
![](http://pbs.twimg.com/media/BBdXj9SCEAIZuUu.png)

**Comment by chelm** [comment]
@ngoldman sounds good! I can use the git logs to refresh my mental history and wll start keeping a legit change log. Thanks for the input.

**Comment by ngoldman** [comment]
@chelm thanks. just trying to do my part to make this awesome project as usable as possible.

**Comment by jgravois** [comment]
i can try and help with maintaining the changelog.  the next step is to start by tagging a release, correct?

**Comment by ngoldman** [comment]
word

ps. word

**Comment by chelm** [comment]
@ngoldman @jgravois This is fun. I added the changelog (for real this time) and tagged some releases. 

going to close this

**Comment by ngoldman** [comment]
:+1:
