### ISSUE TITLE
override any config param via an env var. 

### ISSUE THREAD

**Issue by chelm** [Esri/koop#111]
The idea would be that one could set an ENV var that matches something like `KOOP_*` and would subsequently be lower cased and included in the config object. 

Any existing param would be overridden. 

Is this done anywhere else? @ngoldman @JerrySievert

**Comment by ngoldman** [comment]
Building up constants from an arbitrary list of prefixed environmental variables sounds problematic to me in terms of security. I think it makes more sense to explicitly consume named env vars for sensitive info (e.g tokens) based on what providers are loaded.

With that said, `process.env` exposes a list of environmental variables you could potentially loop through: http://nodejs.org/api/process.html#process_process_env

You could also use a whitelist of valid env vars. Seems like an unnecessary shortcut though.

@JerrySievert thoughts?

**Comment by JerrySievert** [comment]
security, security, security.  the three biggest words in secure computing.

back in the "old days", it was trivial to crack microsoft's frontpage extensions on unix in apache via `ps -aEww` and gain root access.

i would hate to expose koop the same way.  if we allow for it, we would want to be very judicious on what we accept, and not allow any credentials of any sort.

**Comment by chelm** [comment]
@ngoldman @JerrySievert I don't actually have the need for this at the moment but was sparked by @jgravois making a PR that added this to the Github provider but only picked up one env var. 

I was thinking that I'd only ever touch env vars that started with KOOP_. So the user would have to explicitly set something bad in there for it to ever be exposed by koop.

**Comment by JerrySievert** [comment]
@chelm it's not about setting something bad, it's about a multi-tenant machine and credentials.

in the case i was describing with frontpage, they were setting the path the the socket that allowed for any command to be passed in and run as root.

in this case, i was thinking more like:

```
$ KOOP_PROVIDER_USERNAME = myName
$ KOOP_PROVIDER_PASSWORD = myPassword
$ ps -aEww
```

**Comment by chelm** [comment]
I am not actually going to add this.
