### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by muboz** [Esri/koop#113]
Good Day
I'm trying to install koop on windows environment 
 after runnng the command :
 **  npm install koop **
  the cmd prints these errors in the beginning :  

================================================
D:\Projects\Test\ExpressKoop\ExpressKoop\node_modules\koop\node_modules\pg>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
'pg_config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'pg_config --includedir' returned exit status 1. while trying to load binding.gyp
  mapnik@1.4.17 install D:\Projects\Test\ExpressKoop\ExpressKoop\node_modules\koop\node_modules\mapnik
   node-pre-gyp install --fallback-to-build
(mapnik) Success: "D:\Projects\Test\ExpressKoop\ExpressKoop\node_modules\koop\node_modules\mapnik\lib\binding\node-v11-win32-ia32\mapnik.node" is installed via remote
   sqlite3@3.0.5 install D:\Projects\Test\ExpressKoop\ExpressKoop\node_modules\koop\node_modules\spatialite\node_modules\sqlite3
   node-pre-gyp install --fallback-to-build
[sqlite3] Success: "D:\Projects\Test\ExpressKoop\ExpressKoop\node_modules\koop\node_modules\spatialite\node_modules\sqlite3\lib\binding\node-v11-win32-ia32\node_sqlite3.node" is installed via remote
   spatialite@0.0.5 install D:\Projects\Test\ExpressKoop\ExpressKoop\node_modules\koop\node_modules\spatialite
   node-gyp rebuild
D:\Projects\Test\ExpressKoop\ExpressKoop\node_modules\koop\node_modules\spatialite>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
gypWarning: while converting VCCLCompilerTool/CompileAs to MSBuild, invalid literal for int() with base 10: 'CompileAsCpp'
Warning: while converting VCCLCompilerTool/CompileAs to MSBuild, invalid literal for int() with base *10: 'CompileAsCpp'
      Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

================================================
  and in the end of the installation the cmd show these errors:

================================================
gyp
npm ERR! spatialite@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spatialite@0.0.5 install script.
npm ERR! This is most likely a problem with the spatialite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls spatialite
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "koop" "--save"
npm ERR! cwd D:\Projects\Test\ExpressKoop\ExpressKoop
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm

================================================

**Comment by chelm** [comment]
Hello @muboz this is known issue that I'm currentyl working through. I'm aiming to have it working by the end of the week. 

It requires me making some changes that make things like mapnik and spatialite optional plugins rather than require modules.

**Comment by chelm** [comment]
@muboz Hi - I just looked more closely at your command above. Do you have PostGIS installed locally? That seems to be the error that you're getting. Regardless you wont *have* to have in the future, but it is the preferred cache for koop.

**Comment by slibby** [comment]
@muboz also make sure that your postgresql /bin folder is in your system path, and that you can execute "pg_config" from cmd. Then you should be able to get past that error.

I would also recommend trying to get github.com/chelm/koop-sample-app running instead of just /koop.

**Comment by muboz** [comment]
@slibby 
it works now after i configured the system Path .. thanks alot silbby

@chelm thanks :)

**Comment by ngoldman** [comment]
@chelm @slibby @muboz marking this as resolved unless there are objections.

**Comment by slibby** [comment]
@ngoldman It can be closed for now, but I think there are larger issues with Windows installs that will need to be "addressed" -- they can be reserved for separate issues.

**Comment by ngoldman** [comment]
@slibby agreed, we should capture the larger windows bug/challenge in a new issue

**Comment by chelm** [comment]
@slibby what still needs to be addressed? Or are we good now that we've removed mapnik as a required dep?

**Comment by slibby** [comment]
@chelm we're good, this can stay closed and we'll open a new one if any windows bugs come up.
