### ISSUE TITLE
speed up travis-ci testing

### ISSUE THREAD

**Issue by ngoldman** [Esri/koop#114]
There are two things that can be done to speed up testing with travis-ci:

1. [cache `node_modules`](http://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/)
2. [enable docker](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)

@bcomnes showed me these tweaks in `gh-release` (https://github.com/ngoldman/gh-release/blob/master/.travis.yml#L6-L9)  and they make tests run a whole lot faster.

@chelm do you know if your tests require `sudo`? If they do then the docker part won't work, otherwise I can open a PR adding both of these to `.travis.yml`.

**Comment by chelm** [comment]
@ngoldman tests should not require sudo

**Comment by ngoldman** [comment]
Added these suggestions in #117 -- merging that will automatically close this issue.

**Comment by ngoldman** [comment]
I just realized although there is a `.travis.yml` file in the repo, the tests aren't being run by travis. @chelm did you add it then turn it off? I'm guessing it wasn't working because of tests requiring PostGIS or something like that.

**Comment by chelm** [comment]
@ngoldman Ahh yes! The travis CI stuff was never finished because of postgis but that should not be a blocker anymore. Let's turn it on.
