### ISSUE TITLE
stale branches

### ISSUE THREAD

**Issue by ngoldman** [Esri/koop#118]
All branches other than master look pretty stale https://github.com/Esri/koop/branches/all

![screen shot 2015-03-12 at 4 32 00 pm](https://cloud.githubusercontent.com/assets/427322/6630366/704cc3c8-c8d5-11e4-92ea-aba65aa8e09b.png)

There are some commits that haven't been merged here and there but it looks like they're all a year out of date. @chelm do you want to keep these around or is it OK if I delete them?

**Comment by chelm** [comment]
@ngoldman yes those can all go

**Comment by ngoldman** [comment]
Alright, they've all been nuked!
