### ISSUE TITLE
Refactor Exporter to support saving previous export versions 

### ISSUE THREAD

**Issue by chelm** [Esri/koop#120]
In coordination with some with in ArcGIS Open Data we'd like koop to support serving the saved versions of exported data. To koop this just means doing exactly what its doing now except any time it creates a new file it will copy the file into a "latest" subdir on the s3 bucket. 

the file name will be `{:item_id}_{:layer_id}.{:format}`

**Comment by ngoldman** [comment]
Is the idea to cache the download state so the same state can be downloaded later?

**Comment by dmfenton** [comment]
@ngoldman this issue is in support of https://github.com/ArcGIS/composer/issues/7271

TL:DR if a download for a dataset ever worked, open data could call straight to s3 in the case of any general or acute outage.

**Comment by chelm** [comment]
The idea is to always have the last available export on hand in s3. It would be overwritten each time we create a new file, and protect against things we're seeing in production where either the service becomes temporarily unavailable or our network routing goes down. The thought is that open data can call s3 directly and check for a file, the UI would give the user an option to download the preview version.

**Comment by ngoldman** [comment]
Ah ok that makes sense.

**Comment by ngoldman** [comment]
@chelm has this been resolved by https://github.com/Esri/koop/pull/133 or was that just a clean up prior to this task?

**Comment by chelm** [comment]
This is resolved by #133, closing
