### ISSUE TITLE
Remove mapnik/tiles from being a required part of koop deploys

### ISSUE THREAD

**Issue by chelm** [Esri/koop#121]
Mapnik and all the things it brings to koop should be done in a separate module. There are some things that need to thought about though: 

1. Removal of all tile specific code from koop
2. how will providers with tile endpoints still be able to generate tiles 
3. if "tiles" becomes a plugin, what is the pattern for "registering a plugin". 
4. Where does the plugin code live? in Esri github, in @chelm's github, or?

**Comment by chelm** [comment]
@ngoldman Would be good to get your opinion on this. I have the work essential done (I've extracted the tile generation code into a separate module), but the big question is how directly would a "plugin" be tied to koop. i.e. do we create a generic mapnik module that just take data and renders it to a given file and then we have "koop-tiles" plugin that wraps that. Or do we just have a koop-tiles plugin...

**Comment by ngoldman** [comment]
@chelm if it can be generalized to something usable (and hopefully useful) outside of koop, I say make it a generic module and wrap it. That way we're (a) decoupling feature functionality from plugin architecture as much as possible, (b) contributing to the node & open source ecosystem by making something that can easily be used elsewhere. Does that make sense?

**Comment by chelm** [comment]
@ngoldman it does. The decoupling is also nice as it will give us the freedom to potentially change how we generate tiles, esp if something already exists (which it might). Thanks. I'll probably have a couple new repos and a PR that will add the idea of registering plugins to koop. Will let you know when I have something to share.

**Comment by ngoldman** [comment]
@chelm cool, sounds good. It looks like what's emerging is a lightweight koop core module that consumes both data provider modules and utility/feature/bonus plugin modules.

**Comment by chelm** [comment]
@ngoldman yup, will be cool

**Comment by ngoldman** [comment]
I think this has been resolved by https://github.com/Esri/koop/pull/122, but I'm afraid this might be a breaking change which was not properly reflected in the versioning or changelog.

https://github.com/Esri/koop/blob/master/CHANGELOG.md#110---2015-03-17 implies that the change is non-breaking but I'm guessing if you just update to the latest version of koop 1.x and expect tiles to still be there you will be disappointed. @chelm?

**Comment by slibby** [comment]
:+1:

**Comment by chelm** [comment]
Going to close this and address the versioning in a new issue.
