### ISSUE TITLE
Can ArcMap connect to a koop instance?

### ISSUE THREAD

**Issue by prashtx** [Esri/koop#125]
I've tried adding the demo koop service to ArcMap 10.2 via "Add ArcGIS Server", but it looks like ArcMap depends on some API calls that are missing. Is there a way to add a koop FeatureServer/layer directly to ArcMap? If not, do you know what pieces might be needed to bridge the gap? Thanks!

**Comment by chelm** [comment]
Great question. Let me try hooking up a service arcmap myself and see what request it is making. I remember someone talking about some different types of requests but I cant recall what they were. 

@astauffer or @slibby might have some insight. Will report back soon @prashtx

**Comment by slibby** [comment]
So, I took a look at connecting to a koop.dc.esri.com sample from gist, and it *does not* work from ArcMap. the two JSON responses from /item=<uri>?f=json are below:

Koop-service:
{
    "id": "a6f777a8650844bd868f2b1b2bd9e1f1",
    "item": "http://koop.dc.esri.com/gist/6021269/FeatureServer/0",
    "itemType": "url",
    "owner": "slibby_dbsne",
    "uploaded": 1426796064000,
    "modified": 1426796064000,
    "guid": null,
    "name": null,
    "title": "Koop-FS",
    "type": "Feature Service",
    "typeKeywords": [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "Service"
    ],
    "description": null,
    "tags": [
        "koop"
    ],
    "snippet": null,
    "thumbnail": null,
    "documentation": null,
    "extent": [
        [
            -119.0039,
            50.2893
        ],
        [
            -119.0039,
            50.2893
        ]
    ],
    "lastModified": -1,
    "spatialReference": null,
    "accessInformation": null,
    "licenseInfo": null,
    "culture": "en-us",
    "properties": null,
    "url": "http://koop.dc.esri.com/gist/6021269/FeatureServer/0",
    "access": "private",
    "size": 52,
    "appCategories": [],
    "industries": [],
    "languages": [],
    "largeThumbnail": null,
    "banner": null,
    "screenshots": [],
    "listed": false,
    "ownerFolder": null,
    "protected": false,
    "commentsEnabled": false,
    "numComments": 0,
    "numRatings": 0,
    "avgRating": 0,
    "numViews": 0
}

Hosted Feature Service: 
{
    "id": "1f7bf6170e464e77a8a4ab2590b3a6ba",
    "item": "http://services1.arcgis.com/BteRGjYsGtVEXzaX/arcgis/rest/services/NC_East/FeatureServer",
    "itemType": "url",
    "owner": "slibby_dbsne",
    "uploaded": 1426619189000,
    "modified": 1426619840000,
    "guid": null,
    "name": null,
    "title": "NC_East",
    "type": "Feature Service",
    "typeKeywords": [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "Service",
        "Singlelayer",
        "Hosted Service"
    ],
    "description": null,
    "tags": [],
    "snippet": null,
    "thumbnail": null,
    "documentation": null,
    "extent": [
        [
            -79.8169978777596,
            34.01250445768857
        ],
        [
            -77.3691134357975,
            36.2273882980663
        ]
    ],
    "lastModified": -1,
    "spatialReference": null,
    "accessInformation": null,
    "licenseInfo": null,
    "culture": "english (united states)",
    "properties": null,
    "url": "http://services1.arcgis.com/BteRGjYsGtVEXzaX/arcgis/rest/services/NC_East/FeatureServer",
    "access": "private",
    "size": 87,
    "appCategories": [],
    "industries": [],
    "languages": [],
    "largeThumbnail": null,
    "banner": null,
    "screenshots": [],
    "listed": false,
    "ownerFolder": null,
    "protected": false,
    "commentsEnabled": false,
    "numComments": 0,
    "numRatings": 0,
    "avgRating": 0,
    "numViews": 15
}

So far, one area that might be easy to fix would be the differences in typeKeywords:

**Comment by chelm** [comment]
@slibby do you think the keywords would break arcmap though? I'm thinking its something to do with arcmap making POST requests to the koop that may or may not be correctly supported

**Comment by slibby** [comment]
@chelm as ArcMap has no way to add a koop feature service in an ad-hoc fashion, this has to be tested by adding items to ArcGIS Online which are pointers to Koop-based services. Then loading these items into ArcMap

**Comment by astauffer** [comment]
@slibby If you do this, ArcMap and Pro still fail to load the item. I'll try to get a repro case infront of an engineer to take a look at to see what's missing in koop. I thought there was a problem with the default renderer before... but could be thinking of something different.

**Comment by jseppi** [comment]
@astauffer Any updates on how to get Koop-generated FeatureServices into ArcMap?

**Comment by slibby** [comment]
@chelm one thing I noticed when trying to add a koop-gist FS to Pro was that it makes a POST request 
```
POST http://koop.dc.esri.com/gist/6021269/FeatureServer HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
User-Agent: ArcGIS Pro
Host: koop.dc.esri.com
Content-Length: 6
Connection: Keep-Alive
Pragma: no-cache

f=json
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=utf-8
Date: Fri, 29 May 2015 11:34:31 GMT
X-Content-Type-Options: nosniff
Content-Length: 40
Connection: keep-alive

Cannot POST /gist/6021269/FeatureServer
```
Which 404s. Maybe need to support POST returning basic endpoint JSON metadata?

**Comment by slibby** [comment]
I was able to get a gist added to Pro following these steps:
1. update koop-gist/routes/index.js to:
```
module.exports = {
  'get /gist/:id/FeatureServer/:layer/:method': 'featureservice',
  'post /gist/:id/FeatureServer/:layer/:method': 'featureservice',
  'get /gist/:id/FeatureServer/:layer': 'featureservice',
  'post /gist/:id/FeatureServer/:layer': 'featureservice',
  'get /gist/:id/FeatureServer': 'featureservice',
  'post /gist/:id/FeatureServer': 'featureservice',
  'get /gist/:id.:format': 'find',
  'get /gist/:id': 'find',
  'get /gist/raw/:id': 'find',
  'get /gist/raw/:id/:layer': 'find',
  'get /gist': 'index',
  'get /gist/:id/preview' : 'preview'
}
```
2. Create a web map with a koop-gist layer in it
3. Open ArcGIS Pro
4. Load webmap from your Portal
5. Layer is added but does not appear, change map projection to WGS84
6. Voila!

So, I think the new issue is that Koop so far doesn't respect POST requests with outSR defined, so a POST request with ourSR=102100 returns degrees still:
```
POST http://saml.esri.com:1337/gist/6021269/FeatureServer/0/query HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
User-Agent: ArcGIS Pro
Host: saml.esri.com:1337
Content-Length: 453
Connection: Keep-Alive
Pragma: no-cache

f=json&outFields=id&where=1%20%3d%201&returnGeometry=true&maxAllowableOffset=5826.9648813041658&outSR=%7b%22wkid%22%3a102100%2c%22latestWkid%22%3a3857%7d&geometry=%7b%22xmin%22%3a-16235866.480940506%2c%22ymin%22%3a435080.04447070649%2c%22xmax%22%3a-4298357.7607753668%2c%22ymax%22%3a9389182.7454081066%2c%22spatialReference%22%3a%7b%22wkid%22%3a102100%2c%22latestWkid%22%3a3857%7d%7d&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 513
ETag: W/"201-a6a763bc"
Date: Fri, 29 May 2015 12:32:25 GMT
Connection: keep-alive

{"objectIdFieldName":"id","globalIdFieldName":"","hasZ":false,"hasM":false,"geometryType":"esriGeometryPolygon","spatialReference":{"wkid":4326},"fields":[{"name":"id","type":"esriFieldTypeOID","alias":"id"}],"features":[{"geometry":{"rings":[[[-119.00390625,50.28933925329178],[-102.48046875,53.014783245859206],[-82.79296874999999,39.639537564366684],[-91.7578125,32.84267363195431],[-116.19140625,29.38217507514529],[-119.00390625,50.28933925329178]]],"spatialReference":{"wkid":4326}},"attributes":{"id":1}}]}
```

**Comment by chelm** [comment]
@slibby yup. Each provider has to add the post routes which is sort of annoying. 

If you look at the controller for koop-socrata you'll we map the POST body onto the `req.query` in order to behave the same. 

Make sense?

**Comment by dmfenton** [comment]
Closing, issues should be logged against specific providers that don't work.
