### ISSUE TITLE
doc site plan

### ISSUE THREAD

**Issue by ngoldman** [Esri/koop#128]
Koop needs a website! For docs, providers, plugins, example apps, tutorials.

Some possible goals:

* simplify README.md, move detailed doc to a website and expand it
* provide an index for growing number of adapters and plugins, both official (https://github.com/koopjs) and unofficial
* provide sample starter apps & mini-tutorials for different use cases (like https://github.com/koopjs/koop-tiles-app)

Proposed name: `koopjs.com` (currently available: http://who.is/whois/koopjs.com)

> See https://github.com/Esri/koop/pull/127#issuecomment-83726970

**Comment by chelm** [comment]
This is great.

**Comment by ngoldman** [comment]
Working on doc site at http://github.com/koopjs/koopjs.github.io
