### ISSUE TITLE
`config.server.port` still in use?

### ISSUE THREAD

**Issue by ngoldman** [Esri/koop#131]
Is `config.server.port` still being used by koop?

e.g.

* https://github.com/Esri/koop/blob/master/README.md#registering-providers
* https://github.com/koopjs/koop-sample-app/blob/master/config/default.json#L3
* https://github.com/jgravois/koop-heroku-edn/blob/master/server.js#L3

I haven't been able to find any internal references to it in this repo. If it's just being used by express to define the port and not creating a secondary port for koop, it should be removed from documentation and samples.

**Comment by chelm** [comment]
:+1:

**Comment by chelm** [comment]
@ngoldman The `config.server` param is just telling express what port to use at startup. Its used at the "app" level, not the koop module level. So it makes sense to remove it from the default config in the module. 

The documentation is a high priority of mine this week. First need to get the readme up-to-date and start work on over all koop docs that cover koop, providers and apps.
