### ISSUE TITLE
Serve KMZ instead of KML

### ISSUE THREAD

**Issue by dmfenton** [Esri/koop#132]
KML are HUGE, let's save some space on the wire and in local storage.

**Comment by slibby** [comment]
As far as I can tell, this would be pretty easy:
- change name of output to doc.kml (as specified by kmz doc)
- put it in a folder
- rename the folder to the desired output name (:id)
- zip folder and rename to .kmz

This would be caught in some logic at https://github.com/Esri/koop/blob/36dea37f408782d273a99b6322414b2bcffbccfe/lib/Exporter.js#L292

**Comment by ajturner** [comment]
All data will gzip over the wire dynamically if the browser requests (and all modern ones do) – so there is likely little benefit to sending a KMZ vs. a KML in any known use cases.


On 3/26/15, 11:03 PM, "Sam Libby" <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I can tell, this would be pretty easy:

  *   change name of output to doc.kml (as specified by kmz doc)
  *   put it in a folder
  *   rename the folder to the desired output name (:id)
  *   zip folder and rename to .kmz

This would be caught in some logic at https://github.com/Esri/koop/blob/36dea37f408782d273a99b6322414b2bcffbccfe/lib/Exporter.js#L292

**Comment by dmfenton** [comment]
Cool. I'm reading up on https://developers.google.com/web/fundamentals/performance/index?hl=en
Enjoying their style of technical explanations.



On Sun, Mar 29, 2015 at 11:39 AM -0700, "Andrew Turner" <notifications@github.com<mailto:notifications@github.com>> wrote:

All data will gzip over the wire dynamically if the browser requests (and all modern ones do) – so there is likely little benefit to sending a KMZ vs. a KML in any known use cases.


On 3/26/15, 11:03 PM, "Sam Libby" <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I can tell, this would be pretty easy:

* change name of output to doc.kml (as specified by kmz doc)
* put it in a folder
* rename the folder to the desired output name (:id)
* zip folder and rename to .kmz

This would be caught in some logic at https://github.com/Esri/koop/blob/36dea37f408782d273a99b6322414b2bcffbccfe/lib/Exporter.js#L292
