### ISSUE TITLE
Major version bump

### ISSUE THREAD

**Issue by chelm** [Esri/koop#135]
Due to a breaking change in #122 We need to bump the major version. 

The plan: 

1. depricate the 1.1.* releases
2. added [YANKED] to change log for those 3 releases
3. bump koop version to 2.0.0 on the upcoming release today

@ngoldman, @JerrySievert sound good?

**Comment by ngoldman** [comment]
@chelm we'd need to do the same for 1.1.1 and 1.1.2 as well.

@JerrySievert for reference the [YANKED] nomenclature comes from http://keepachangelog.com/#what-about-yanked-releases-

**Comment by chelm** [comment]
will update the above

**Comment by ngoldman** [comment]
@chelm you can [npm unpublish](https://docs.npmjs.com/cli/unpublish) specific versions but they say the following in the doc:

> It is generally considered bad behavior to remove versions of a library that others are depending on!

We could also [npm deprecate](https://docs.npmjs.com/cli/deprecate) the versions in question. This would provide a warning when npm installing without removing them altogether.

**Comment by ngoldman** [comment]
(so maybe deprecating instead of removing 1.1.*)

**Comment by chelm** [comment]
@ngoldman done. I'm going to go ahead an do this today if that's cool.

**Comment by ngoldman** [comment]
okay @chelm. be careful, this is a big one! let me know if I can help at all.
