### ISSUE TITLE
koop on Windows running under iisnode

### ISSUE THREAD

**Issue by sirws** [Esri/koop#142]
I have been able to make some progress and was able to get koop to run on windows.  My next hurdle is that I want it to run in a more “production” way.  I have been playing with iisnode:
 
https://github.com/tjanczuk/iisnode
 
Which looks like it should do what I want to do which is access the koop node app via IIS.  I have it up and running, but I can’t seem to quite get it, although I think I am close.
 
Here is the URL to node/IIS:
http://50.18.49.187/node/
 
the koop app is in there:
http://50.18.49.187/node/koop/server.js (returns a 404)
 
You can look at the logs here:
http://50.18.49.187/node/koop/iisnode/
 
Any ideas or help on this would be great. I am more than happy to write this stuff up for the wiki if we can get it working for our windows koop users.

**Comment by chelm** [comment]
@slrws Great! 

Can you post some more info and what steps you've followed to get the app up and running and maybe post your web.config file? 

I'm trying to understand how it tells koop to start up and on what port. You may need to change you config file to use port 80 or something too. Maybe share the config file you are using as well.

**Comment by sirws** [comment]
Ok, here you go...

Install iisnode 64-bit for IIS7 from here:
https://github.com/azure/iisnode/releases/download/v0.2.16/iisnode-full-v0.2.16-x64.msi

This lays down the binaries and creates an application in IIS called node:
http://50.18.49.187/node/

It is basically a virtual directory pointing to c:\program files\iisnode\www

I then copied the koop install folder into that folder:
![image](https://cloud.githubusercontent.com/assets/793576/7006800/c157fc6c-dc38-11e4-9cbd-5369f1898508.png)

Here is the koop folder:
![image](https://cloud.githubusercontent.com/assets/793576/7006810/db4a96c0-dc38-11e4-9a48-c27d6999ad72.png)

I put a web.config in that folder that looks like this:
<configuration>
  <system.webServer>

    

    <handlers>
      <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
    </handlers>
    
	<rewrite>
		<rules>
           <rule name="server">
             <match url="server/*" />
             <action type="Rewrite" url="server.js" />
           </rule>
		</rules>
	</rewrite>
	
  </system.webServer>
</configuration>

Basically, the web config says that anything that calls server.js (or anything under server using URL rewrite rules, will cause the node server to process it, instead of iis.  Other files that aren't handled in the web.config just get processed by IIS.  Like this: http://50.18.49.187/node/koop/readme.html

So, the idea is that IIS is running on port 80 and when necessary will start up node to do the processing when requested.

For example, this app that is installed with iisnode:
http://50.18.49.187/node/configuration/readme.htm
Has some good info about how it uses node to process hello.js:
http://50.18.49.187/node/configuration/hello.js
Then, you can look at the logs:
http://50.18.49.187/node/configuration/iisnode/

This is the contents of hello.js:
var http = require('http');

http.createServer(function (req, res) {
    console.log('A new request arrived with HTTP headers: ' + JSON.stringify(req.headers));
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end('Hello, world! [configuration sample]');
}).listen(process.env.PORT);

console.log('Application started at location ' + process.env.PORT);

**Comment by sirws** [comment]
FYI, the logs for koop on this server can be accessed here:
http://50.18.49.187/node/koop/iisnode/

When you try and run this:
http://50.18.49.187/node/koop/server.js

It adds log output to the http://50.18.49.187/node/koop/iisnode/ location.

**Comment by chelm** [comment]
@slrws So looking at this file: http://50.18.49.187/node/koop/iisnode/IP-0A7461A7-7388-stdout-1428335953472.txt

The first line on the stdout has "Listening at http://undefined:NaN/" Which tells me that koop might not know what port its using (:NaN) that could be one issue

**Comment by sirws** [comment]
I added a couple of console.log statements in server.js:

app.listen(process.env.PORT || config.server.port,  function() {
  console.log(process.env.PORT);
  console.log(config.server.port);
  console.log("Listening at http://%s:%d/", this.address().address, this.address().port);
});

And this is the output:
http://50.18.49.187/node/koop/iisnode/IP-0A7461A7-11432-stdout-1428337041006.txt

so process.env.PORT and config.server.port seem to be set...

**Comment by chelm** [comment]
@sirws Cool. I'm still confused about how it all works. Need to read the docs more. It is permissions? http://50.18.49.187/node/koop/

the other thing that seems wierd is having server.js in the url. Typically a node app runs a file like `server.js` and that exposes routes like `github/*`

**Comment by sirws** [comment]
Yah, I think I need to do a little more of the URL rewriting to deal with the URLs properly.  Take a look at these docs:
http://50.18.49.187/node/urlrewrite/readme.htm

**Comment by sirws** [comment]
I am wondering if any issues have to do with the fact that I installed koop from here:
https://github.com/koopjs/koop-sample-app

**Comment by sirws** [comment]
@chelm Ok, I made some progress.  I think it has to do with the fact that the app is not at the root of the IIS server.  So, koop is at /node/www/koop and when I go to access the /socrata endpoint, I see that node is trying to access /node/koop/socrata and returning a 404 because I believe the koop node server expects it to be at the /socrata location.  When I move the app to the root of IIS, it works!  Great progress, but I would like to be able to put the node app in a sub folder of the root of the web server.

http://50.18.49.187/socrata/wa/42qd-frvg/FeatureServer works!

would love to have it at:
http://50.18.49.187/koop/socrata/wa/42qd-frvg/FeatureServer

Any thoughts?  Also, this is a good overview of iisnode:

http://www.jokecamp.com/blog/getting-started-with-iisnode/

**Comment by slibby** [comment]
@sirws can this be closed now? Based on your recent gist and pending incorporating that into the Readme

**Comment by sirws** [comment]
Yes.  I may open a new issue though that has to do with running koop at a location other than /.  In my case, it doesn't run at the root of the web server, it runs at /koop.  I have worked around it PARTIALLY by updating the routes on the github and socrata providers.  It would be great to update koop to allow it to run at something other than /.  Maybe a user specified root in the server js?

**Comment by sirws** [comment]
Here is the gist:
https://gist.github.com/sirws/af77f664da000f295f6d

**Comment by chelm** [comment]
@sirws Checkout this line: https://github.com/koopjs/koop-sample-app/blob/master/server.js#L60

You can pass a route to Express' `use` method like `app.use('/koopness', koop)` 

The koop object there is just express middleware which means it can be mounted at any route. Checkout this for more details: http://expressjs.com/guide/using-middleware.html

**Comment by sirws** [comment]
Cool!  So, I made that change and it works pretty well.  But, i think a number of other issues are popping up.  i.e. when I visit this URL: http://50.18.49.187/koop/github the map doesn't seem to load properly because there is a request being sent to: http://50.18.49.187/js/map.js that is returning a 404...

Is there something simple I need to do for that?  

Also these lines need to be changed as well:
https://github.com/koopjs/koop-sample-app/blob/master/server.js#L69
```
app.get("/koop", function(req, res, next) {
```
https://github.com/koopjs/koop-sample-app/blob/master/server.js#L62
```
app.get('/koop/status', function(req, res){
```

**Comment by sirws** [comment]
@chelm Also, I updated the gist.  Take a look at number 12 and make sure it makes sense to you.

**Comment by chelm** [comment]
@sirws Okay cool, looks good. 

Bullet 12: Yes looks good. Should probably make the `/koop/status' route part of koop but not crucial. 

The github map issue is probably an issue we need to deal with. I'll have to look at it but its trying to pull some shared code from from koop that should proably be controlled in the middleware so it respects the non root mount points. Will make a new issue.
