### ISSUE TITLE
Support standalone TLS encryption

### ISSUE THREAD

**Issue by slibby** [Esri/koop#152]
While koop is often deployed behind another webserver, reverse proxy, or load balancer, with TLS terminated at that server, if standalone Koop is required/wanted, the web service should ideally support HTTP and HTTPS connections, not HTTP-Only. This will also support end-to-end encryption required for some environments.

Could start with ```tls``` module and then move towards supporting CA-signed certificates, etc.

Koop should be configurable to support user-defined ports for HTTP/TLS, 1337 and 1443 for example.

**Comment by ngoldman** [comment]
@slibby isn't koop currently only able to be express middleware? does middleware need to handle TLS or can the parent express app handle that?

**Comment by chelm** [comment]
right koop is just middleware so this would make sense within the various koop-apps right? We could produce a demo app that shows how to do this

**Comment by slibby** [comment]
My mistake, I'll move this to koop-sample-app when I get it working.
