### ISSUE TITLE
Koop Performance with Large Datasets

### ISSUE THREAD

**Issue by pholleran** [Esri/koop#157]
When requesting large datasets from the cache Koop is taking a long time to return data to the browser. It would be nice if there were a way to speed it up.

http://koop.dc.esri.com/socrata/detroitmi/vxm7-i6zf/featureServer/0

![skitch](https://cloud.githubusercontent.com/assets/4007128/7397716/ecbbe712-ee6f-11e4-936b-7642413b66ee.png)

**Comment by chelm** [comment]
There are ways to make this faster, esp with geom based bbox queries. I need to revisit using indexes in the DB

**Comment by ngoldman** [comment]
indexes :+1:

**Comment by chelm** [comment]
Sweet so I added a GIST index on this dataset locally and it took the query time for a box that returns 49k features down from 7sec to 20ms... so yeah pretty smart to add the index on table creation. Easy to add too. So i'll make the change tomorrow.

**Comment by chelm** [comment]
actually the issue here is that the current indexes in koop-pgcache were (a) indexing on empty geom fields and (b) choking on the table names. Have it fixed and flying.

**Comment by chelm** [comment]
PR submitted to koop-pgcache

**Comment by ajturner** [comment]
:rocket:

**Comment by chelm** [comment]
@pholleran it's "a bit" faster :) http://www.arcgis.com/home/webmap/viewer.html?url=http://koop.dc.esri.com/socrata/detroitmi/vxm7-i6zf/featureServer/0

closing this

**Comment by pholleran** [comment]
Awesome! I owe you some IPAs next time I see you :beers:
