### ISSUE TITLE
For "Error 'null' occurred reading

### ISSUE THREAD

**Issue by ValueCreation** [Esri/koop#161]
https://koopsample2.herokuapp.com/
I tried to make a similar environment to heroku.

Several times when you access the following URL
https://koopsample2.herokuapp.com/gist/6021269/FeatureServer/0

The following error message is displayed.
"Error 'null' occurred reading from https://api.github.com/gists/6021269"

Once you have direct access from this URL it does not seem to be a problem.
https://api.github.com/gists/6021269

I wonder if there is something cause.

**Comment by chelm** [comment]
It looks like this might be happening when you hit the rate limits for github. Are you specififying a Github API Token?  If not, try adding this to your config file: 

```javascript
  ...
  "ghtoken": "XXXXXXXXXXXXXXXXXXXXXXX",
  ...
```

**Comment by chelm** [comment]
@ValueCreation if you dont have an API key for Github your can create one in your account settings. 

This is just a guess at the possible solution, and I think whats needed is a better error report for when this happens.

**Comment by ValueCreation** [comment]
Thanks you
  "ghtoken": "XXXXXXXXXXXXXXXXXXXXXXX"
After adding the problem it is unlikely.

https://koopsample2.herokuapp.com/github/chelm/grunt-geo/forks
https://koopsample2.herokuapp.com/github/chelm/grunt-geo/forks/FeatureServer/0
https://koopsample2.herokuapp.com/github/smartchicago/chicago-atlas/db::import::zipcodes/FeatureServer/0/query?geometry=-180,-90,180,90
In the case of,
"No geojson found"
It will be displayed.

This is also how do I have to set something, what the configuration of github side.

**Comment by chelm** [comment]
@ValueCreation Sorry, I'm a bit confused. When and where do you see "No geojson found"? Typically that means the data in Github is not parsing as geojson inside koop. The links you sent in the comment above both work for me.

**Comment by ValueCreation** [comment]
Sorry,
At first it has been successfully display, which is also after you have accessed several times, for some reason,
"No geojson found"
It will be displayed.

https://koopsample2.herokuapp.com/github/chelm/grunt-geo/forks
In you will heroku log of when you have access.

2015-05-05T00:12:06.169764+00:00 heroku[router]: at=info method=GET path="/github/chelm/grunt-geo/forks" host=koopsample2.herokuapp.com request_id=80dc649d-f6a6-4e54-abec-1b774293ea71 fwd="111.107.162.66" dyno=web.1 connect=2ms service=49ms status=500 bytes=234
2015-05-05T00:12:06.123910+00:00 app[web.1]: /github/chelm/grunt-geo/forks undefined {} {}
2015-05-05T00:12:06.169027+00:00 app[web.1]: /github/chelm/grunt-geo/forks 500

It will become error because the status is 500.

**Comment by chelm** [comment]
@ValueCreation Can you paste your config/default.json file for me?

**Comment by ValueCreation** [comment]
Sorry.
config/default.json are set as follows.

```
{
  "server": {
  "port": 1337
},
  "data_dir": "/usr/local/koop/",
  "db": {
      "conn": "postgres://localhost/koopdev"
   },
  "ghtoken": "207c08170b411be1bb5a0bbfb64aa7c92baf0320"
}
```
As a reminder, default_https.json has been set as follows.
```
{
    "server": {
        "port": 1337
    },

        "https_server": {
                "port": 1443,
                "private_key" : "cert/private.pem",
                "public_key" : "cert/public.pem"
         },

    "data_dir": "/usr/local/koop/",
    "db": {
      "conn": "postgres://localhost/koopdev"
    },
    "ghtoken": "207c08170b411be1bb5a0bbfb64aa7c92baf0320"
}
```

**Comment by ValueCreation** [comment]
@chelm 
I'm sorry
Is it all right in this setting basically.
It would help us if you would tell me if there is a place where there is a problem.

**Comment by chelm** [comment]
@ValueCreation Everything looks good to me. I'm having trouble reproducing the issue of "No geojson found". I have not been able to get the same error, but that error come from the koop-github provider when it tries to parse data from github and cannot find any valid GeoJSON. To me this sounds like its still a rate limit issue where Github starts blocking requests after the rate limits are reached. I am not 100% sure about that though.

I wish I could be more helpful, but I'll need to get the problem to occur locally.

**Comment by ValueCreation** [comment]
I'm sorry,
I understand.

Indeed, it is likely there is also the possibility.

Thanks you.
We'll try a little more confirmed in my way.

Please say if there is a means to confirm something.
