### ISSUE TITLE
"Error converting data to geojson" using Socrata provider

### ISSUE THREAD

**Issue by sirws** [Esri/koop#165]
Here is a sample dataset:
http://koop.dc.esri.com/socrata/wastate/3rgj-95q8/FeatureServer

Here is the source:
https://data.wa.gov/Natural-Resources-Environment/TMDL-Effectiveness-Monitoring-projects/3rgj-95q8?

**Comment by slibby** [comment]
Looks like https://data.wa.gov/resource/3rgj-95q8.json returns ```[]```

Not sure why.

**Comment by slibby** [comment]
It looks like this dataset only allows re-download, not querying through SODA: https://data.wa.gov/Natural-Resources-Environment/TMDL-Effectiveness-Monitoring-projects/3rgj-95q8 
c.f. to
https://data.wa.gov/Procurements-and-Contracts/OCIO-IT-Project-Oversight-Leadership-Details/3uf4-3kn2?

**Comment by dmfenton** [comment]
All non-point spatial data are going to have this problem. We need to get a story about handling these types. Should-be straight forward to bring in shapefiles and convert to geojson with something like https://github.com/geopipes/shapefile-stream or just vanilla ogr2ogr

**Comment by chelm** [comment]
@sirws I think this should be a feature request as an issue in koop-socrata.
