### ISSUE TITLE
error: start up obj=true

### ISSUE THREAD

**Issue by kpettijohn** [Esri/koop#170]
Not sure if this is truly an issue or not but whenever I start `koop` I get the following log/error printed to console.

```
node server.js

Database koopdev has already been created... skipping.
Starting the koop server...
error: start up obj=true
Express koop server listening on port 8000
``` 
https://github.com/Esri/koop/blob/master/index.js#L263

**Comment by chelm** [comment]
Heh yes my fault this snuck in from some log testing I was doing. Going to remove it via PR tonight. 

Thanks @kpettijohn
