### ISSUE TITLE
Simple GeoJSON provider

### ISSUE THREAD

**Issue by jseppi** [Esri/koop#174]
Is there just a simple Koop provider that takes an in-memory or on-disk geojson and serves that as a FeatureService?

**Comment by chelm** [comment]
@jseppi There was in the very beginning, but so much changed and it was sort of left behind as an idea. We were always planning on bringing it back if the need ever arose. 

It'd be very straightforward to write, and I could be convinced to possible create it this week... :)

**Comment by jseppi** [comment]
@chelm We could definitely use it here at TNRIS. We're trying to get some current Texas flood information up and out the door, and would really like to have FeatureServices for our ArcMap users. We've standardized on using GeoJSON as an intermediary conversion between other state and local live data sources.  

It does seem like it should be fairly simple but I'm short on time right now in understanding what needs to be done for creating a new provider. If you have some guidance for that I could also give it a shot.

**Comment by chelm** [comment]
@jseppi why not just upload the data to Github and use the github koop provider? It could be ready to use today!

**Comment by jseppi** [comment]
Yeah, that's a decent idea. The data (closures due to high water crossings for instance) are rapidly changing so we'd have to upload with some frequency.

**Comment by dmfenton** [comment]
Every gist is just a git repo. So you don't so much have to upload as simply git-push.
https://help.github.com/articles/about-gists/

**Comment by jseppi** [comment]
I've written most of a simple koop-geojson-file provider that fulfills my needs. Once I've finished with it I'll post the repo here.

**Comment by jseppi** [comment]
Here it is: https://github.com/jseppi/koop-geojson-file
Also published to `npm`

**Comment by chelm** [comment]
@jseppi Very nice! Love it.
