### ISSUE TITLE
GeoRSS to Feature Service

### ISSUE THREAD

**Issue by mhogeweg** [Esri/koop#185]
Is there an adapter/pipeline to consume a GeoRSS and expose this as a feature service that can be consumed in the JS API?

**Comment by chelm** [comment]
@mhogeweg I don't think there has been talk of a GeoRSS provider in Koop. One issue that this raises is that koop has no way to proxy artibrary URLs. There would need to be a sort of rss feed index somewhere it can use to reference feed. 

For instance this url would not work in arcgis.com: 

`www.koop.com/georss/FeatureServer/0?url=http://some.example.com/feed.rss`

it would need to be something like: 

`www.koop.com/georss/{FEED-ID}/FeatureServer/0` and so on...

**Comment by mhogeweg** [comment]
there may be some ways around that by encoding the URL (which is an identifier after all) in some way:

``` www.koop.com/georss/http__some_example_com_feed.rss/FeatureServer/0 ```

but that may have it's own limitations (as the RSS feed may result from complex web service request).

In this case, we do have a catalog (Geoportal Server) where the feed could be stored and accessed based on the ID of the feed in the catalog.

**Comment by chelm** [comment]
Okay great. The pattern we use elsewhere is one where we "register" a host into koop and give it an id: 

http://koop.dc.esri.com/socrata

We should do something similar here with Geoportal server. In terms of converting GeoRSS to GeoJSON (which then gets stored and turned into FeatureService JSON) we could build on top of something like https://www.npmjs.com/package/georsstogeojson

**Comment by mhogeweg** [comment]
That's what I did with a Geoportal adapter I got running. Next would be to access information within this Geoportal, some of which may be the rss or a feature service already registered.

**Comment by dmfenton** [comment]
Merging with #106
