### ISSUE TITLE
Unexpected 'OPERATOR' exception from featureservice

### ISSUE THREAD

**Issue by PeaceNlove** [Esri/koop#192]
I was playing around with my new provider in Arcgis Online and tried to change the rendering style to Counts and Amounts (Size) and I clicked options. 
From the network panel in chrome I can see the following URL
http://localhost:1337/cbs/70262ned/time/2010/Featureserver/0/query?f=json&returnIdsOnly=true&returnCountOnly=true&where=Bos_29%20%3E%3D%200%20AND%20Bos_29%20%3C%201657.1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&maxAllowableOffset=2445&outFields=*&outSR=102100&callback=dojo.io.script.jsonp_dojoIoScript31._jsonpCallback

As far as I know, this URL should be processed and give a result in Koop

However, I get an exception and the stacktrace below:

debug: Selecting data select id, feature->>'properties' as props, feature->>'geometry' as geom from "CBS:70262ned:2010:0" WHERE  (feature->'properties'->>'Bos_29')::float::int >= 0 AND  (feature->'properties'->>'Bos_29')::float < 1657.1 ORDER BY id
D:\Koop\koop-sample-app\node_modules\koop\node_modules\sql-parser\lib\compiled_parser.js:182    throw new Error(str);
          ^
Error: Parse error on line 2: Unexpected 'OPERATOR'
    at Object.parseError (D:\Koop\koop-sample-app\node_modules\koop\node_modules\sql-parser\lib\compiled_parser.js:182:11)
    at Object.parse (D:\Koop\koop-sample-app\node_modules\koop\node_modules\sql-parser\lib\compiled_parser.js:258:22)
    at Object.exports.parse (D:\Koop\koop-sample-app\node_modules\koop\node_modules\sql-parser\lib\parser.js:28:26)
    at Object.exports.parse (D:\Koop\koop-sample-app\node_modules\koop\node_modules\sql-parser\lib\sql_parser.js:10:27)
    at Object.module.exports.whereFilter (D:\Koop\koop-sample-app\node_modules\koop\lib\Query.js:386:21)
    at Object.module.exports.filter (D:\Koop\koop-sample-app\node_modules\koop\lib\Query.js:11:12)
    at Object.module.exports.send (D:\Koop\koop-sample-app\node_modules\koop\lib\FeatureServices.js:289:11)
    at Object.module.exports.query (D:\Koop\koop-sample-app\node_modules\koop\lib\FeatureServices.js:253:14)
    at Object.processFeatureServer (D:\Koop\koop-sample-app\node_modules\koop\lib\BaseController.js:63:47)
    at D:\Koop\koop-sample-app\node_modules\koop-nl-cbs\controller\index.js:36:20

http://localhost:1337/cbs/70262ned/time/2010/Featureserver/0/query?f=json&returnIdsOnly=true&returnCountOnly=true&where=Bos_29%20%3E%3D%200%20AND%20Bos_29%20%3C%201657.1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&maxAllowableOffset=2445&outFields=*&outSR=102100&callback=dojo.io.script.jsonp_dojoIoScript31._jsonpCallback

**Comment by chelm** [comment]
@PeaceNlove This looks like to be an issue with the SQL parsing in the the `koop-pgcache` module. Is there a way you can get me the data you are testing this with? In some form that I can host on github or elsewhere?

**Comment by PeaceNlove** [comment]
I made the geojson from Koop and saved it here: https://github.com/PeaceNlove/Koop-testdata
then, requested this data as feature service via the github provider in Koop and there it works as expected and the urls which went wrong with my provider work fine with the github provider. 
I compared the urls and logged console lines and there is no difference.

So I think the problem is in my provider since the data, url parameters and logs look the same.
Maybe you can have a look at my code to see if I did something wrong? https://github.com/PeaceNlove/koop-nl-cbs (you wont get it working since the table necessary for this provider isn't included)

**Comment by chelm** [comment]
@PeaceNlove Okay that really helps. I think I have an idea. 

I'm willing to bet that even though the github provider is not crashing or erroring it is probably not actually applying the where filter on the data. In fact it's removing the `where` filter all together (https://github.com/koopjs/koop-github/blob/master/controller/index.js#L176). It does this because koop has been using the PostGIS cache for so long that the providers are assuming the sql parsing/filters and spatial filtering is happening at the DB level. 

So I think the solution here is to either use `koop-pgcache` AND delete the `req.query.where` in your controller's feature server method. Then what we really need to do is get koop's `lib/Cache.select` method parsing the sql and applying the filter on the data (which will be tricky)

Make sense?

**Comment by PeaceNlove** [comment]
Adding the 'delete req.query.where' line solved the problem.
I changed this in the sample-provider as well and created a pull request in the koop-sample-provider so others using the sample won't have this problem again.

Thanks for the quick response :-)
