### ISSUE TITLE
make everything streams 

### ISSUE THREAD

**Issue by chelm** [Esri/koop#8]
Everything should be operating on node streams, this will improve performance and will allow better chaining of filter processes.

**Comment by chelm** [comment]
@dmfenton why close this? Everything is not streams...

**Comment by dmfenton** [comment]
True, but didn't see the value in leaving issues around from August 2013. I think we should revisit this piece by piece.

**Comment by chelm** [comment]
fine fine, but I'd see is closed with a link to something actionable like "implement a streaming interface to lib/Geojson" I can create that though

**Comment by dmfenton** [comment]
fair enough :+1:

**Comment by ngoldman** [comment]
@dmfenton was going to ask the same about other issues -- if they're not resolved they shouldn't be closed without an explanation or a link.
