### ISSUE TITLE
npm install fails on spatialite module due to GLIBC_2.14 not found on RHEL6 / CentOS6

### ISSUE THREAD

**Issue by soichih** [Esri/koop#80]
Hi. I am trying to give this package a spin on my development instances (RHEL6 and CentOS6).

At the moment, I am failing to run "npm install" on newly git cloned directory. The README says that this is tested on Ubuntu. Does this mean koop won't run on GLIBC_2.12 environment (like RHEL6?)

Following is the npm output snippet..

> sqlite3@2.2.7 install /usr/local/koop/node_modules/koop-server/node_modules/spatialite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v11-linux-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v11-linux-x64.tar.gz
[sqlite3] Command failed:
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/koop/node_modules/koop-server/node_modules/spatialite/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile

Thank you!

**Comment by dmfenton** [comment]
spatialite has been removed as a dependency
