### ISSUE TITLE
error when performing analysis on koop feature services in the ArcGIS Online map viewer.

### ISSUE THREAD

**Issue by jgravois** [Esri/koop#95]
steps to repro:
1. load [this](http://koop.dc.esri.com/github/colemanm/hurricanes/fl_2004_hurricanes/FeatureServer/0) service in a new ArcGIS Online webmap (or open [this](http://esrihack.maps.arcgis.com/home/webmap/viewer.html?webmap=f176aabcf2b542f6991b98cdbb108486) one)
2. right click the layer and select 'perform analysis' to run a 5 mile buffer on a subset of the points.
3. an error is encountered stating that the input is invalid and no output is written.

i was able to repro on a fresh local install of koop.  the behavior is the same with [this](http://koop.dc.esri.com/socrata/seattle/2tje-83f6/FeatureServer/0) socrata endpoint.

i haven't been able to determine what AGOL doesn't like about the layers yet.

**Comment by dmfenton** [comment]
The fix was merged
